### ISSUE TITLE
Bad DateTimeOffset serialization format

### ISSUE THREAD

**Issue by AntoineMarques** [microsoft/kiota-serialization-json-php#33]
I believe serialization of DateTime is wrong, because of the trailing `Z` in format.
`RFC3339 `already contains time offset, then Z conflicts with it.

`JsonSerializationWriter::testWriteDateTimeOffsetValue()` shows that expected output is like `2018-12-12T12:34:42+00:00Z`.

But this format isn't accepted by MS Graph which fails saying :
```
{
    "error": {
        "code": "UnableToDeserializePostBody",
        "message": "were unable to deserialize "
    }
}
```

Of course if i remove the trailing, everything works.
Here's a [demo](https://github.com/microsoft/kiota-serialization-json-php/files/11615469/test.txt) with a calendar event payload.
Faulty fields are `createdDateTime` and `lastModifiedDateTime`

**Comment by Ndiritu** [comment]
@AntoineMarques this fix has been released. `composer update` should resolve.
