### ISSUE TITLE
PHP float parsing returns null when the number is an int

### ISSUE THREAD

**Issue by galrito** [microsoft/kiota-serialization-json-php#86]
### What are you generating using Kiota, clients or plugins?

API Client/SDK

### In what context or format are you using Kiota?

Nuget tool

### Client library/SDK language

PHP

### Describe the bug

For properties declared as a `number` (or `float`) on the API spec, if the API returns a value for that property as an integer (e.g. `3`, as opposed to `3.0`), the generated PHP Kiota client returns the value as a null.

### Expected behavior

According to JSON Schema, integers numbers as values for floats properties are also expected. As such, the PHP Kiota client should be parsing the integer value as a float instead of null. For example, a float property to hold prices could be represented with the forms `4` or `4.00` and both should be accepted as the same float value.

https://json-schema.org/understanding-json-schema/reference/numeric#number

### How to reproduce

Generate a Kiota PHP client and call the "/products" service on the Open API file below and observe the `price` values.

### Open API description file

https://github.com/galrito/kiota-deserializer-php-bug-example/blob/main/openapi.yaml

### Kiota Version

1.18.0+5c6b5d0ef23865ba2f9d9f0b9fe4b944cf26b1ec

### Debug output

<details><summary>Click to expand log</summary>
```


<log output here>

```
</details>

### Other information

The problem lies on the implementation of `getFloatValue()` that should also be expecting an int

https://github.com/microsoft/kiota-serialization-json-php/blob/a60319f9a47e5f3f241768463b67b20649f9cdea/src/JsonParseNode.php#L76

**Comment by baywet** [comment]
Hi @galrito
Thank you for using kiota and for reaching out.
Since you've already started a pull request, we'll continue the conversation over there.
